[tasks.wasm_watch]
workspace = false
script = ["cd wasm_client", "wasm-pack build --debug"]
watch = { no_git_ignore = false, watch = [
    "./wasm_client/",
    "./database/",
    "./common/",
] }

[tasks.view_serve]
workspace = false
script = ["cd view", "ng serve"]


[tasks.serve_watch]
workspace = false
run_task = { name = ["wasm_watch", "view_serve"], parallel = true }
