[tasks.install]
workspace = false
description = "Install all dependencies"
script = ["cd view", "npm i"]

[tasks.wasm_watch]
workspace = false
script = ["cd wasm_vgc", "wasm-pack build --debug"]
watch = { no_git_ignore = false, watch = [
    "./wasm_vgc/",
    "./vgc/",
    "./common/",
] }

[tasks.view_serve]
workspace = false
script = ["cd view", "ng serve"]


[tasks.serve_watch]
workspace = false
run_task = { name = ["wasm_watch", "view_serve"], parallel = true }
