extend = [
    { path = "makefile/lint.toml" },
    { path = "makefile/clean.toml" },
    { path = "makefile/serve.toml" },
    { path = "makefile/build.toml" },
]

[tasks.build-web]
workspace = false
description = "Build production angular webapp"
run_task = [
    { name = [
        "wasm_build",
        "view_npm_install",
        "view_build",
    ], parallel = false },
]

[tasks.build-desktop]
workspace = false
description = "Build desktop application and installer and webapp"
run_task = [
    { name = [
        "wasm_build",
        "view_npm_install",
        "tauri_build",
    ], parallel = false },
]

#Serve web angular
[tasks.serve]
workspace = false
description = "Serve angular webapp and watch for changes"
run_task = [{ name = ["install", "serve_watch"], parallel = false }]


[tasks.lint]
workspace = false
description = "Check all lint errors and show them"
run_task = [
    { name = [
        "cargo_lint",
        "view_lint",
        "view_prettier",
    ], parallel = false },
]

[tasks.lint-fix]
workspace = false
description = "Fix all lint errors and format code"
run_task = [
    { name = [
        "cargo_lint_fix",
        "view_lint_fix",
        "view_prettier_fix",
    ], parallel = false },
]


[tasks.clean-all]
workspace = false
description = "Clean all unnecessary files"
run_task = { name = [
    "view_clean",
    "wasm_clean",
    "cargo_clean",
], parallel = true }

[tasks.test-all]
workspace = false
description = "Run all tests"
run_task = { name = ["cargo_test", "view_test"], parallel = false }
