#Serve web angular
[tasks.serve]
workspace = false
run_task = [
    { name = ["wasm_build_all", "view_install", "view_serve"] },
]

#Build and install for serve

[tasks.wasm_build_all]
workspace = false
run_task = [{ name = ["wasm_vgc_build"], parallel = true }]

[tasks.wasm_vgc_build]
workspace = false
script = ["cd wasm_vgc", "wasm-pack build"]

[tasks.view_install]
workspace = false
script = ["cd view", "npm i"]

[tasks.view_serve]
workspace = false
script = ["cd view", "ng serve"]

#Clean all non necessary files
[tasks.clean_all]
workspace = false
description = "Clean all files"
run_task = { name = ["view_clean", "wasm_clean","cargo_clean"], parallel = true }


#Clean specific

[tasks.cargo_clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.view_clean]
workspace = false
run_task = [
    { name = "view_clean_win", condition = { platforms = ["windows"] } },
    { name = "view_clean_unix", condition = { platforms = ["mac", "linux"] } }
]

[tasks.view_clean_unix]
workspace = false
command = "rm"
args = ["-rf", "view/node_modules"]

[tasks.view_clean_win]
workspace = false
script = "if exist \"view/node_modules\" rmdir /s /q \"view/node_modules\""

[tasks.wasm_clean]
workspace = false
run_task = [
    { name = "wasm_clean_win", condition = { platforms = ["windows"] } },
    { name = "wasm_clean_unix", condition = { platforms = ["mac", "linux"] } }
]

[tasks.wasm_clean_unix]
workspace = false
command = "rm"
args = ["-rf", "wasm_vgc/pkg"]

[tasks.wasm_clean_win]
workspace = false
script = "if exist \"wasm_vgc/pkg\" rmdir /s /q \"wasm_vgc/pkg\""