extend = [{ path = "makefile/lint.toml" }, { path = "makefile/clean.toml" }]


#Serve web angular
[tasks.serve]
workspace = false
#TODO : do not serve angular every time
run_task = [{ name = ["wasm_build_all", "view_serve"] }]
watch = { no_git_ignore = false, watch = ["./wasm_vgc/", "./vgc/"] }

[tasks.install]
workspace = false
run_task = [{ name = ["wasm_build_all", "view_install", "view_serve"] }]

[tasks.lint]
workspace = false
run_task = [
    { name = [
        "cargo_lint",
        "view_lint",
        "view_prettier",
    ], parallel = false },
]

[tasks.lint-fix]
workspace = false
run_task = [
    { name = [
        "cargo_lint_fix",
        "view_lint_fix",
        "view_prettier_fix",
    ], parallel = false },
]


[tasks.wasm_build_all]
workspace = false
run_task = [{ name = ["wasm_vgc_build"], parallel = true }]

[tasks.wasm_vgc_build]
workspace = false
script = ["cd wasm_vgc", "wasm-pack build --debug"]

[tasks.view_install]
workspace = false
script = ["cd view", "npm i"]

[tasks.view_serve]
workspace = false
script = ["cd view", "ng serve"]


[tasks.clean-all]
workspace = false
description = "Clean all unnecessary files"
run_task = { name = [
    "view_clean",
    "wasm_clean",
    "cargo_clean",
], parallel = true }
