[package]
name = "vgc"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
float-cmp = "0.9.0"
tiny-skia = "0.11.1"
postcard = { version = "1.0.0", features = ["alloc"] }
serde = { version = "1.0.*", default-features = false }

iced = { version = "0.10.0", features = ["canvas"] }