name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: 1.79
    - name: Run test
      run: cargo test
    - name: Build Wasm lib
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 0.12.1
    - name: Buid wasm-client js package
      working-directory: ./wasm_client
      run: wasm-pack build
    - uses: actions/setup-node@v1
      with:
        node-version: latest
    - name: npm install
      run: npm ci
    - name: Frontend test
      run: ng test
        
